export const alcohols = [
    'Absinthe',
    'Armagnac/French Brandy',
    'Baiju',
    'Beer-Dark',
    'Beer-Light',
    'Beer-Guinness',
    'Bourbon',
    'Brandy', 
    'Calvados',
    'Champagne-Gossett', 
    'Champagne-Jacquat', 
    'Champagne-Hamm', 
    'Champagne-Korbel', 
    'Champagne-Moet', 
    'Champagne-Chandon',
    'Cider, Hard',
    'Cognac',
    'EverClear',
    'Frangelico',
    'Gin',
    'Grand Marnier',
    'Grappa',
    'Grenadine',
    'Jägermeister',
    'Kahlua',
    'Kirschwasser',
    'Liqueurs',
    'Margarita',
    'Martini',
    'Mead',
    'Ouzo',
    'Pisco',
    'Port Wine',
    'Rum',
    'Sherry',
    'Southern Comfort',
    'Tequila',
    'Triple Sec',
    'Vermouth',
    'Vodka',
    'Whiskey, Scotch',
    'Whisky, Irish',
    'Wine, Red',
    'Wine, White',
    'Wine, Sulfite Free'
];